
name: Upload coverage report

on:
  workflow_run:
    workflows: ["CI pipeline for pySDC"]
    types: ["completed"]
  
jobs:
  upload_coverage:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.repository_owner == 'Parallel-in-Time'
      && github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: "etc/environment-postprocess.yml"
      - name: Downloading artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.ACTION_READ_TOKEN }}
      - name: Prepare artifacts
        run: |
          python -m coverage combine coverage_*.dat
          python -m coverage xml
          python -m coverage html
      - name: Generate Coverage badge
        run: |
          genbadge coverage -i coverage.xml -o htmlcov/coverage-badge.svg
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV }}
